#title in header
title: "å—¨ï¼Œæ‚¨å¥½ã€‚"

#main info
#owner
owner: "lee-ping"
info: "çŸ³æ¤æˆç¾ï¼Œæ„§è¿¨åŒç°ä¹‹è¯®ã€‚"
#description
desc: "Helloï¼Œæ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ã€‚ğŸ˜"

#menu
menu:
  é¡¹ç›®: /projects
  å…³äº: /leeping

#index/main page max show posts (in number)
max_post: 3

# social profile at the footer/bottom
place: https://www.baidu.com/s?wd=æ˜†æ˜
github: https://github.com/ping-lee
instagram: http://wpa.qq.com/msgrd?v=3&uin=1179320194&site=qq&menu=yes
twitter: https://u.wechat.com/EBPGXLkxm4Gttz60TaK6AhA

# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.ico

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: tristanme-com

lazyload:
  enable: true
  # thumbPath: '/images/thumb'
  # className: #optional e.g. .J-lazyload-img
  # loadingImg: #optional eg. /images/loading.png