#title in header
title: "å—¨ï¼Œæ‚¨å¥½ã€‚"

#main info
#owner
owner: "lee-ping"
info: "å¸é«˜é˜³ä¹‹è‹—è£”å…®ï¼Œæœ•çš‡è€ƒæ›°ä¼¯åº¸ã€‚æ‘„æè´äºå­Ÿé™¬å…®ï¼ŒæƒŸåºšå¯…å¾ä»¥é™ã€‚çš‡è§ˆæ†ä½™äºåˆåº¦å…®ï¼Œè‚‡é”¡ä½™ä»¥å˜‰åï¼šåä½™æ›°æ­£åˆ™å…®ï¼Œå­—ä½™æ›°çµå‡ã€‚"
#description
desc: "ä½ å¥½å‘€ï¼Œæ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ğŸ˜"

#menu
menu:
  é¡¹ç›®: /projects
  å…³äº: /leeping

#index/main page max show posts (in number)
max_post: 3

# social profile at the footer/bottom
place: https://www.google.com/search?q=æ˜†æ˜
github: https://github.com/ping-lee
instagram: https://www.instagram.com/ping-lee/
twitter: https://twitter.com/ping-lee

# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.ico

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: tristanme-com
